<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="LoginPage.css">
	<meta charset="UTF-8" />
	<title>Book Events</title>
</head>
<body>
<ul id="NavBar">
    <li><a href="index.php">Home</a></li>
    <li><a href="LoginPage.php">Login</a></li>
    <li><a href="Credits.php">Credit</a></li>
    <li><a href="orderBooksForm.php">Order</a></li>
    <li><a href="AdminPage.php">Admin Page</a></li>

    <?php
    if(isset($_SESSION['logged-in'])) {
        if ($_SESSION['logged-in'] === true) {
            echo "<a href='logoutScript.php'>Logout</a>";

        }
        else {
            echo "<form method='post' action='LoginPageScript.php'>
        <fieldset>
            Username <input type='text' name='username' />
            Password <input type='password' name='password' />
            <input type='submit' value='Login' />
        </fieldset>
        </form>";
        }
    }
    else{
        echo "<form method='post' action='LoginPageScript.php'>
        <fieldset>
            Username <input type='text' name='username' />
            Password <input type='password' name='password' />
            <input type='submit' value='Login' />
        </fieldset>
        </form>";
    }
    ?>
</ul>
<?php
/* This code dynamically generates a web page containing a form designed with the html required to display one
checkbox for each of the books currently held in the nbc_books database table has been provided for you in the
assessment section for the module on blackboard. The user can select one or more books that they are interested in
ordering by clicking the checkboxes.
Use the browser to look at the structure of the html generated by the php code. */

$url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/orderBooksFormInc.php";
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($curl);
curl_close($curl);
echo $result;
?>

<!-- Here you need to add Javascript or a link to a script to process the form as required for the assignment -->
<script>
    window.addEventListener('load', function initialise () {
        'use strict';
        var frm = document.getElementById('orderForm');


        function checkForm(theForm) {
            "use strict";


            if (theForm.forename.value.trim() === '') {
                // not firstname entered
                alert("You have not entered a name");
                return false;
            }
            if (theForm.surname.value === '') {
                // no last name chosen
                alert("You did not select a surname");
                return false;
            }
            // if the script gets this far it means it didn't return false and so
            // everything is ok - returning true will allow the form to be submitted
            return true;
        }
       // frm.deliveryType.onclick = totalPrice;


        document.querySelector('section[id="collection"]').onchange=totalPrice;

        var aInputElements = frm.getElementsByTagName("input");
        for(var k = 0; k < aInputElements.length; k++){
            aInputElements[k].onchange = totalPrice;
        }

        function totalPrice() {
                var aInputElements = frm.getElementsByTagName("input");
                var price = 0;
                //get all input boxes exect the last three that are not usfull in the calculation of price
                for (var y = 0; y < aInputElements.length - 3; y++) {
                    //store a refernce to a Input Elements[counter] into current element;
                    var currentElement = aInputElements[y];
                    //if currentElement is a checkbox and current element is checked then
                    if (currentElement.type === 'checkbox' && currentElement.checked) {
                        //total <- total + currentElement.value;
                        price += parseFloat(currentElement.dataset.price);


                    }
                    //end if

                    //end for
                }

                //iterate throught the delivery (checkboxes for shipping)array
                for (var n = 0; n < frm.deliveryType.length; n++) {
                    //if the element checked then
                    if (frm.deliveryType[n].checked) {
                        //add to total
                        price += parseFloat(frm.deliveryType[n].dataset.price);
                    }

                    frm.total.value = "£" + price.toFixed(2);
                }
            }



            });

</script>
<script>
    window.addEventListener('load', function initialise () {
        'use strict';
        var frm = document.getElementById('orderForm');

        function checkReadTerms() {
            var submit = this.form.querySelector('input[type=submit]');
            submit.disabled = !this.checked;
            /* use ternary if to change the parent label colour based on
             whether the checkbox is checked or not.
             In fact I should also check the parentNode type to ensure
             it's a label.
             */
            this.parentNode.style.color = (this.checked) ? 'black' : 'red';
        }

        frm.termsChkbx.onchange = checkReadTerms;
    });


</script>
<script>
    window.addEventListener('load', function initialise () {
        'use strict';
        var frm = document.getElementById('orderForm');

        document.querySelector('select[name="customerType"]').onchange=changeCustomerType;

        function changeCustomerType() {
            //works
            var selected = this.options[this.selectedIndex].value;
            var Customerdivs = document.getElementById('retCustDetails');
            var Tradedivs = document.getElementById('tradeCustDetails');
            if(selected === 'ret'){
                Customerdivs.style.display = "block";
                Tradedivs.style.visibility = "hidden";
            }
            if(selected === 'trd'){
                Tradedivs.style.visibility = "visible";
                Customerdivs.style.display = "none";

            }
            totalPrice();
        }
    });


</script>
</body>
</html>